CREATE TABLE `har_db`.`Entires` (
  `EntryID` INT NOT NULL AUTO_INCREMENT,
  `Domain` VARCHAR(100) NOT NULL COMMENT '	',
  `StartedDateTime` DATETIME NOT NULL COMMENT '		',
  `TotalTime` FLOAT NOT NULL,
  `RequestCacheControl` VARCHAR(45) NULL,
  `RequestDate` DATETIME NULL COMMENT '	',
  `RequestUserAgent` VARCHAR(512) NULL,
  `RequestHeaderSize` INT NULL,
  `RequestBodySize` INT NULL,
  `ResponseDate` DATETIME NULL,
  `ResponseLastModified` DATETIME NULL,
  `ResponseServer` VARCHAR(128) NULL,
  `ResponseLength` INT NULL,
  `ResponseStatus` INT NULL,
  `ResponseHeaderSize` INT NULL,
  `ResponseBodySize` INT NULL,
  `ResponseHttpVersion` VARCHAR(45) NOT NULL,
  `ResponseTransferSize` INT NULL,
  `Blocked` FLOAT NOT NULL,
  `DNS` FLOAT NOT NULL,
  `Connect` FLOAT NOT NULL,
  `Send` FLOAT NOT NULL,
  `Wait` FLOAT NOT NULL,
  `Receive` FLOAT NOT NULL,
  `SSLTime` FLOAT NOT NULL,
  `ComputerType` VARCHAR(45) NULL,
  `ConnectionPath` VARCHAR(45) NULL,
  PRIMARY KEY (`EntryID`));

